[package]
name = "native-dialog"
version = "0.6.4"
authors = ["balthild <ibalthild@gmail.com>"]
edition = "2018"
description = "A library to display dialogs. Supports GNU/Linux, BSD Unix, macOS and Windows."
license = "MIT"
documentation = "https://docs.rs/native-dialog"
repository = "https://github.com/balthild/native-dialog-rs"

[dependencies]
thiserror = "1.0.19"
dirs-next = "2.0.0"
raw-window-handle = "0.4.2"
ascii = "1.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
wfd = "0.1.7"
winapi = { version = "0.3", features = ["winuser"] }
once_cell = { version = "1.4.0", optional = true }

[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "ios"), not(target_os = "android")))'.dependencies]
which = "4.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
objc_id = "0.1.1"
objc-foundation = "0.1.1"
block = "0.1.6"
cocoa = "0.24.0"
once_cell = "1.4.0"

[features]
windows_dpi_awareness = []
windows_visual_styles = ["once_cell", "winapi/sysinfoapi", "winapi/winbase", "winapi/handleapi", "winapi/libloaderapi"]

[workspace]
members = [
    "examples/windows_manifest",
    "examples/windows_features",
    "examples/modal_dialog",
]
